use_frameworks!

#source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'CHSVGAPlayer-iOS_Example' do
  pod 'CHSVGAPlayer-iOS', :path => '../'

  target 'CHSVGAPlayer-iOS_Tests' do
    inherit! :search_paths

    
  end
end
